version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  loader:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
